export const divisions = {
	Dhaka: [
		'Dhaka City',
		'Dhaka (District)',
		'Faridpur',
		'Gazipur',
		'Gopalganj',
		'Kishoreganj',
		'Madaripur',
		'Manikganj',
		'Munshigonj',
		'Narayanganj',
		'Narshingdi',
		'Rajbari',
		'Shariatpur',
		'Tangail',
	],
	Rangpur: [
		'Dinajpur',
		'Gaibandha',
		'Kurigram',
		'Lalmonirhat',
		'Nilphamari',
		'Panchagarh',
		'Rangpur',
		'Thakurgaon',
	],
	Chittagong: [
		'Chattogram',
		'Cox’s bazar',
		'Cumilla',
		'B. Baria',
		'Laksmipur',
		'Chandpur',
		'Bandarban',
		'Feni',
		'Khagrachhari',
		'Noakhali',
		'Rangamati',
	],
	Barishal: [
		'Barguna',
		'Barishal',
		'Bhola',
		'Jhalokathi',
		'Potuakhali',
		'Kushtia',
	],
	Khulna: [
		'Bagerhat',
		'Chuadanga',
		'Jashore',
		'Jhenaidah',
		'Khulna',
		'Kushtia',
		'Magura',
		'Meherpur',
		'Narail',
		'Satkhira',
	],
	Sylhet: ['Hobiganj', 'Moulovi Bazar', 'Sunamganj', 'Sylhet'],
	Mymensingh: ['Jamalpur', 'Mymensingh', 'Netrokona', 'Sherpur'],
	Rajshahi: [
		'Bogura',
		'Jaipurhat',
		'Naogaon',
		'Natore',
		'Chapainawabganj',
		'Pabna',
		'Rajshahi',
		'Sirajganj',
	],
};
